package util.lexEnum;

public enum subClass{
    Berserker,
    Path_of_the_Totem_warrior,
    College_of_Lore,
    College_of_Valor,
    Knowledge_Domain,
    Life_Domain,
    Light_Domain,
    Nature_Domain,
    Tempest_Domain,
    Trickery_Domain,
    War_Domain,
    Circle_of_the_land,
    Circle_of_the_moon,
    Champion,
    Battle_master,
    Eldritch_knight,
    Way_of_the_open_hand,
    Way_of_shadow,
    Way_of_the_four_elements,
    Oath_of_devotion,
    Oath_of_the_ancients,
    Oath_of_vengeance,
    Hunter,
    Beast_master,
    Thief,
    Assassin,
    Arcane_trickster,
    Dragonic_bloodline,
    Wild_magic,
    The_fiend,
    The_great_old_one,
    the_archfey,
    School_of_abjuration,
    School_of_conjuration,
    School_of_divination,
    School_of_enchantment,
    School_of_evocation,
    School_of_illusion,
    School_of_necromancy,
    School_of_transmutation;


}
